"""Shared data-provenance notices.

The lake inventory and time-series shipped with this app are generated by
`data/generate_data.py`: real lake names, locations, basins and elevations, but
simulated areas, growth rates, dam types, downstream slopes and settlement
distances. Every page that shows a derived number says so, so nobody mistakes a
demonstration figure for a measured one.
"""
from __future__ import annotations

import streamlit as st

SIMULATED = "simulated"
MEASURED = "measured"

_SIDEBAR_NOTE = "⚠️ Demonstration data — not for operational or emergency use"

_HOME_NOTE = """
**This is a demonstration application, not an operational hazard service.**

Lake names, coordinates, basins, districts and elevations are real. The
**areas, growth rates, dam types, downstream slopes and settlement distances are
simulated** by `data/generate_data.py` — so the hazard scores, risk classes, ML
probabilities and climate projections derived from them are illustrative of the
method, not findings about these lakes.

Population and building counts on the Population Exposure page *are* real
(WorldPop 2020 and OpenStreetMap), but they are summed over flood corridors
drawn from the simulated inventory.

Do not use anything here for planning, early warning or risk communication.
"""


def sidebar_notice() -> None:
    """Persistent one-line warning, shown on every page via app.py."""
    st.caption(_SIDEBAR_NOTE)


def home_notice() -> None:
    """Full provenance explanation for the landing page."""
    st.warning(_HOME_NOTE)


def page_notice(detail: str) -> None:
    """Short per-page note naming which inputs on this page are simulated."""
    st.caption(f"⚠️ Demonstration data — {detail}")
