"""Provenance notice text, rendered by site/build.py.

Kept as data rather than inline HTML so the wording lives in one place and is easy to
review as prose. Markdown-flavoured: **bold**, *italic*, `code` and [links](url) only.
"""

SIDEBAR_NOTICE = "⚠️ Demonstration data — not for operational or emergency use"

HOME_NOTICE = """
**This is a demonstration application, not an operational hazard service.**

Lake names, coordinates, basins, districts and elevations are real. The
**areas, growth rates, dam types, downstream slopes and settlement distances are
simulated** by `data/generate_data.py` — so the hazard scores, risk classes, ML
probabilities and climate projections derived from them are illustrative of the
method, not findings about these lakes.

Population and building counts on the Population Exposure page *are* real
(WorldPop 2020 and OpenStreetMap), but they are summed over flood corridors
drawn from the simulated inventory.

Do not use anything here for planning, early warning or risk communication.
"""

MAP_NOTICE = "hazard scores and risk classes are computed from simulated lake attributes."
TRENDS_NOTICE = "the area series plotted here is simulated, not measured from imagery."
CLIMATE_NOTICE = (
    "the starting area and observed growth rate are simulated. Note also that this is "
    "unconstrained exponential growth: it has no basin, dam-freeboard or meltwater limit, so "
    "values compound indefinitely and the late-century end of the curve should be read as a "
    "trend direction, not a forecast."
)

ML_NOTICE = """
**These probabilities do not measure GLOF risk.** Positive examples come from the event
catalogue and negative examples from the simulated lake inventory, so the classifier can
separate the two classes on artefacts of how each file was written rather than on hazard:
a model trained only on *"is this value a round number?"* separates them perfectly
(AUC 1.00). Cross-validation scores from this setup measure provenance, not skill. Treat
the page as a demonstration of the workflow.
"""

POPULATION_NOTICE = """
The population and building counts here are **real**, but they are summed over flood
corridors derived from the simulated lake inventory — 8 corridors digitised from valley
topography and 17 straight ±2 km centroid paths. The totals are real people counted inside
illustrative corridors, not a flood model.
"""

DOWNLOADS_NOTICE = """
**Lake areas, growth rates, dam types, slopes and settlement distances in these files are
simulated** (`data/generate_data.py`), as are every hazard score, risk class and change
figure derived from them. Population and building counts are real. See the Methodology
page for a full provenance table before reusing any of this data.
"""

METHODOLOGY_NOTICE = """
**The numbers in this app are simulated.** This page documents the method the app
implements and the pipeline it is designed to run on — see *Data Provenance* below for
exactly which values are measured and which are generated.
"""

CACHE_SOURCE_LABELS = {
    "sentinel_hub_mndwi": (
        "Areas are MNDWI-derived Sentinel-2 observations fetched via `data/fetch_sentinel.py`."
    ),
    "demo_cache_from_timeseries": (
        "⚠️ This cache holds **no Sentinel-2 observations**. It was generated by "
        "`data/create_demo_cache.py` from the simulated 2016–2024 area series, so every "
        "change and alert below is a demonstration of the workflow, not a measurement. "
        "Run `data/fetch_sentinel.py` with Sentinel Hub credentials for real scenes."
    ),
    "mixed": "⚠️ Cache mixes real Sentinel-2 scenes with generated demo entries.",
    "unknown": "⚠️ Cache files declare no source — provenance of these areas is unknown.",
}

# Which values in the shipped data are measured, and which are generated.
PROVENANCE_ROWS = [
    ("Lake names, coordinates, basin, district, elevation", "Real — published lake inventories"),
    ("Lake area 2000–2024", "Simulated — data/generate_data.py"),
    ("Area growth rate", "Simulated — data/generate_data.py"),
    ("Dam type", "Simulated — random draw, weighted toward moraine"),
    ("Downstream slope, distance to settlement", "Simulated — random draw"),
    ("Hazard score and risk class", "Computed from the simulated inputs above"),
    ("Sentinel-2 change detection cache",
     "Derived from the simulated series (data/create_demo_cache.py)"),
    ("GLOF event catalogue",
     "Real events, unverified attribute values; HKH-wide, not Nepal-only"),
    ("ML probabilities and climate projections", "Computed from the simulated inputs above"),
    ("Population and building counts", "Real — WorldPop 2020 (100 m) and OpenStreetMap"),
    ("Flood corridors", "8 digitised from valley topography; 17 synthetic centroid paths"),
]
