"""Shared data-provenance notices for the Streamlit app.

The lake inventory and time-series shipped with this app are generated by
`data/generate_data.py`: real lake names, locations, basins and elevations, but
simulated areas, growth rates, dam types, downstream slopes and settlement
distances. Every page that shows a derived number says so, so nobody mistakes a
demonstration figure for a measured one.

The wording lives in utils/provenance_text.py so the static site build renders
exactly the same text.
"""
from __future__ import annotations

import streamlit as st

from utils.provenance_text import HOME_NOTICE, SIDEBAR_NOTICE


def sidebar_notice() -> None:
    """Persistent one-line warning, shown on every page via app.py."""
    st.caption(SIDEBAR_NOTICE)


def home_notice() -> None:
    """Full provenance explanation for the landing page."""
    st.warning(HOME_NOTICE)


def page_notice(detail: str) -> None:
    """Short per-page note naming which inputs on this page are simulated."""
    st.caption(f"⚠️ Demonstration data — {detail}")
