"""Change Detection page — Sentinel Hub baseline vs latest lake area comparison."""
import sys
from pathlib import Path

import plotly.express as px
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.change_detection import compute_changes, get_cache_last_updated, get_cache_source

ROOT = Path(__file__).parent.parent
CACHE_DIR = ROOT / "data" / "sentinel_cache"

_SOURCE_LABELS = {
    "sentinel_hub_mndwi": (
        "Areas are MNDWI-derived Sentinel-2 observations fetched via `data/fetch_sentinel.py`."
    ),
    "demo_cache_from_timeseries": (
        "⚠️ This cache holds **no Sentinel-2 observations**. It was generated by "
        "`data/create_demo_cache.py` from the simulated 2016–2024 area series, so every "
        "change and alert below is a demonstration of the workflow, not a measurement. "
        "Run `data/fetch_sentinel.py` with Sentinel Hub credentials for real scenes."
    ),
    "mixed": "⚠️ Cache mixes real Sentinel-2 scenes with generated demo entries.",
    "unknown": "⚠️ Cache files declare no source — provenance of these areas is unknown.",
}

st.title("Change Detection")
st.markdown(
    "Rapid lake expansion is one of the strongest early-warning signals for GLOF risk — "
    "a growing lake exerts increasing pressure on its dam. This page compares each lake's "
    "earliest cached observation (baseline) against the most recent, flagging any lake "
    "that has grown more than 15% as a potential concern."
)

if not CACHE_DIR.exists() or not any(CACHE_DIR.glob("*.json")):
    st.warning(
        "No Sentinel Hub cache files found. "
        "Run `python data/create_demo_cache.py` to generate demo data, "
        "or `python data/fetch_sentinel.py` with valid API credentials for real data."
    )
    st.stop()

df = compute_changes(cache_dir=str(CACHE_DIR))
last_updated = get_cache_last_updated(str(CACHE_DIR))
cache_source = get_cache_source(str(CACHE_DIR))

st.info(_SOURCE_LABELS.get(cache_source, _SOURCE_LABELS["unknown"]))

# Alert banner
alert_lakes = df[df["alert"]]["lake_name"].tolist()
if alert_lakes:
    st.warning(
        f"**Area change alert (>15%):** {', '.join(alert_lakes)}"
    )
else:
    st.success("No lakes exceed the 15% area change threshold since baseline.")

st.markdown(f"*Cache last updated: {last_updated}*")
st.markdown("---")

# Bar chart
fig = px.bar(
    df,
    x="lake_name",
    y="pct_change",
    color="alert",
    color_discrete_map={True: "#DC503C", False: "#1D9E75"},
    labels={"lake_name": "Lake", "pct_change": "Area Change (%)", "alert": "Alert"},
    title="Lake Area Change Since Baseline (%)",
    hover_data=["baseline_year", "baseline_area", "latest_year", "latest_area", "delta_area"],
)
fig.add_hline(y=15, line_dash="dash", line_color="orange",
              annotation_text="Alert threshold (15%)")
fig.update_layout(height=420, xaxis_tickangle=-35)
st.plotly_chart(fig, width="stretch")

st.markdown("---")

# Data table with trend arrow
def _trend_arrow(pct: float) -> str:
    if pct > 5:
        return "↑"
    elif pct < -5:
        return "↓"
    return "→"

df["trend"] = df["pct_change"].apply(_trend_arrow)

display_df = df[[
    "lake_name", "baseline_year", "baseline_area",
    "latest_year", "latest_area", "delta_area", "pct_change", "trend",
]].rename(columns={
    "lake_name": "Lake",
    "baseline_year": "Baseline Year",
    "baseline_area": "Baseline Area (km²)",
    "latest_year": "Latest Year",
    "latest_area": "Latest Area (km²)",
    "delta_area": "Delta (km²)",
    "pct_change": "Change (%)",
    "trend": "Trend",
})
st.dataframe(display_df, hide_index=True, width="stretch")
